spring:
  application:
    name: AutoWashPro_BE
  datasource:
    url: jdbc:postgresql://localhost:5432/autowashpro
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  docker:
    compose:
      enabled: false

server:
  port: 8080

app:
  jwt:
    secret: AutoWashProSecretKeyForJWT2026MustBeAtLeast256BitsLong!!
    expiration-ms: 86400000
  otp:
    ttl-seconds: 120

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: list
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: INFO
