package com.autowashpro.autowashpro_be.modules.booking.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class MomoPaymentRequest {

    /**
     * MoMo partner code - identifies the merchant/partner
     */
    @JsonProperty("partnerCode")
    private String partnerCode;

    /**
     * Partner name or merchant name
     */
    @JsonProperty("partnerName")
    private String partnerName;

    /**
     * Unique request identifier generated by the merchant (usually timestamp-based)
     */
    @JsonProperty("requestId")
    private String requestId;

    /**
     * Amount in Vietnamese Dong (VND). Must be >= 1,000
     */
    @JsonProperty("amount")
    private Long amount;

    /**
     * Unique order identifier from the merchant system (e.g., booking ID)
     */
    @JsonProperty("orderId")
    private String orderId;

    /**
     * Order information/description (e.g., booking details)
     */
    @JsonProperty("orderInfo")
    private String orderInfo;

    /**
     * URL to redirect customer after successful payment on MoMo
     */
    @JsonProperty("redirectUrl")
    private String redirectUrl;

    /**
     * IPN (Instant Payment Notification) callback URL for backend webhook notifications
     */
    @JsonProperty("ipnUrl")
    private String ipnUrl;

    /**
     * Request type - typically "captureWallet" for MoMo payment gateway
     */
    @JsonProperty("requestType")
    private String requestType;

    /**
     * Language code for MoMo UI ("vi" for Vietnamese, "en" for English)
     */
    @JsonProperty("lang")
    private String lang;

    /**
     * MoMo access key for authentication
     */
    @JsonProperty("accessKey")
    private String accessKey;

    /**
     * HMAC-SHA256 signature of the request payload for security
     */
    @JsonProperty("signature")
    private String signature;

    /**
     * Extra data that can be returned in IPN callback (JSON string format)
     */
    @JsonProperty("extraData")
    private String extraData;
}
